name: Mirror
on: push
jobs:
  build:
    name: Mirror
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Mirror
        env:
          U: jessewilson1
          P: ${{ secrets.BB_PASSWORD }}
        run: |
          git fetch --unshallow origin
          git push -f https://$U:$P@bitbucket.org/jessewilson1/dotfiles.git
